apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: asmha04b8-nodejs
  janus-idp.io/tekton: asmha04b8-nodejs
  backstage.io/kubernetes-id: asmha04b8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: asmha04b8-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
